"""The config builder: a template plus a caller's choices become a validated dataset.

The builder owns **no** validation logic of its own beyond "is this choice on the
menu". Everything that decides whether a configuration is *correct* — does this chain
exist, is this parser registered, is this a known entity label, do the language
settings cohere — belongs to `config/loader.py`, which already knows how to say so
actionably. The builder assembles a document and hands it to that layer.

That split is the point rather than an economy: a service that could validate a
configuration the engine cannot would be owning engine knowledge, which ADR-0025's
rung rule forbids. If the builder ever needs an answer `config/` cannot give, the fix
is a change to `config/`.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from pydantic import ValidationError

from pii_reduction.config import known_labels
from pii_reduction.config.errors import ConfigurationError
from pii_reduction.config.loader import resolve_dataset
from pii_reduction.config.models import DatasetConfig, ProjectConfig
from pii_reduction.config.resolved import ResolvedDataset
from pii_reduction.service.catalog import taken_dataset_names
from pii_reduction.service.errors import InvalidRequestError, UnknownTemplateError
from pii_reduction.service.models import (
    DATASET_NAME_RE,
    BuildConfigRequest,
    ColumnRequest,
)
from pii_reduction.service.templates import DatasetTemplate

__all__ = ["BuiltConfig", "build_dataset_config", "config_path_for", "write_dataset_config"]


@dataclass(frozen=True)
class BuiltConfig:
    """A dataset document that has been through the config layer's own validation."""

    dataset_name: str
    template: str
    payload: dict[str, Any]
    resolved: ResolvedDataset

    def to_yaml(self) -> str:
        header = (
            f"# Generated by the pii-reduction service layer (ADR-0026) from template\n"
            f"# {self.template!r}. Source, destination and the processing switches came\n"
            f"# from that template, not from the request.\n"
        )
        document: str = yaml.safe_dump(self.payload, sort_keys=False, allow_unicode=True)
        return header + document


def _prune(value: Any) -> Any:
    """Drop empty containers and ``None`` so the generated YAML reads like a hand file."""
    if isinstance(value, dict):
        pruned = {k: _prune(v) for k, v in value.items() if v is not None}
        return {k: v for k, v in pruned.items() if v != {} and v != []}
    return value


def _require_on_menu(chosen: str, offered: tuple[str, ...], *, what: str, template: str) -> str:
    if chosen not in offered:
        raise InvalidRequestError(
            f"template {template!r} does not offer {what} {chosen!r}; "
            f"available: {', '.join(sorted(offered)) or '(none)'}"
        )
    return chosen


def _column_payload(
    request: ColumnRequest,
    template: DatasetTemplate,
    project: ProjectConfig,
    offered_entities: tuple[str, ...],
) -> dict[str, Any]:
    for label in request.entities:
        _require_on_menu(label, offered_entities, what="entity", template=template.name)
    payload: dict[str, Any] = {"entities": sorted(set(request.entities))}
    if request.parser is not None:
        payload["parser"] = _require_on_menu(
            request.parser, template.offered_parsers(), what="parser", template=template.name
        )
    if request.reducer is not None:
        payload["reducer"] = _require_on_menu(
            request.reducer, template.offered_reducers(), what="reducer", template=template.name
        )
    if request.provider_chain is not None:
        offered = template.provider_chains or tuple(sorted(project.chains))
        payload["provider_chain"] = _require_on_menu(
            request.provider_chain, offered, what="provider chain", template=template.name
        )
    return payload


def build_dataset_config(
    request: BuildConfigRequest,
    *,
    templates: dict[str, DatasetTemplate],
    project: ProjectConfig,
) -> BuiltConfig:
    """Assemble the document, then let the configuration layer accept or refuse it.

    Raises :class:`UnknownTemplateError` or :class:`InvalidRequestError` for a choice
    that is not on the menu, and lets `config`'s own ``ConfigurationError`` through
    for anything the configuration layer refuses — its messages name the field and
    the file and are already written to be shown to somebody.
    """
    template = templates.get(request.template)
    if template is None:
        raise UnknownTemplateError(
            f"unknown template {request.template!r}; "
            f"available: {', '.join(sorted(templates)) or '(none)'}"
        )

    _require_on_menu(
        request.row_id,
        template.offered_row_id_columns(),
        what="row id column",
        template=template.name,
    )
    seen: set[str] = set()
    for column in request.columns:
        _require_on_menu(column.column, template.columns, what="column", template=template.name)
        if column.column in seen:
            raise InvalidRequestError(f"column {column.column!r} is listed twice")
        seen.add(column.column)
        if column.column == request.row_id:
            raise InvalidRequestError(
                f"column {request.row_id!r} is the row identifier and cannot also be reduced"
            )

    offered_entities = template.entities or tuple(sorted(known_labels()))
    payload: dict[str, Any] = {
        "dataset": {"name": request.dataset_name, "row_id": request.row_id},
        "source": _prune(template.source.model_dump(mode="json", by_alias=True)),
        "destination": _prune(template.destination.model_dump(mode="json", by_alias=True)),
        "columns": {
            column.column: _column_payload(column, template, project, offered_entities)
            for column in request.columns
        },
    }
    if template.processing is not None:
        processing = _prune(template.processing.model_dump(mode="json"))
        if processing:
            payload["processing"] = processing
    if template.language is not None:
        language = _prune(template.language.model_dump(mode="json"))
        if language:
            payload["language"] = language

    try:
        dataset = DatasetConfig.model_validate(payload)
    except ValidationError as exc:
        # A pydantic error here is a *configuration* problem — almost always a
        # template field the dataset model refuses — and must not reach the API's
        # last-resort handler as `unexpected ValidationError`. Rendered as
        # `field.path: message`, never echoing the offending value.
        details = "; ".join(
            f"{'.'.join(str(part) for part in error['loc']) or '<root>'}: {error['msg']}"
            for error in exc.errors()
        )
        raise ConfigurationError(
            f"template {template.name!r} cannot produce a valid dataset ({details})"
        ) from exc
    resolved = resolve_dataset(dataset, project)
    return BuiltConfig(
        dataset_name=request.dataset_name,
        template=template.name,
        payload=payload,
        resolved=resolved,
    )


def config_path_for(configs_dir: Path, dataset_name: str) -> Path:
    """Where a built config is written. Derived by the server, never sent by a caller.

    ``dataset_name`` has already been validated against
    :data:`~pii_reduction.service.models.DATASET_NAME_PATTERN`, so it cannot contain a
    separator, a dot or a leading digit — the property that makes this a join rather
    than a path-traversal surface. Re-checked here anyway, because this function is
    reachable from anywhere in the package and the check is one line.
    """
    if not DATASET_NAME_RE.match(dataset_name):
        raise InvalidRequestError(
            f"dataset name {dataset_name!r} is not a valid identifier "
            "(lower-case letters, digits and underscores; 3-64 characters)"
        )
    return configs_dir / "datasets" / f"{dataset_name}.yaml"


def write_dataset_config(built: BuiltConfig, configs_dir: Path) -> Path:
    """Write the document, refusing to replace one that exists.

    Fail-closed for the same reason ``errorifexists`` is the Delta default: a builder
    that silently overwrites a configuration somebody is running turns a naming
    collision into a change of behaviour for a job nobody edited.

    ``open(..., "x")`` rather than ``exists()`` then write: the check and the write are
    one operation, so two requests naming the same dataset cannot both pass the check.
    The message names the **dataset**, not the path — a path is a server-environment
    string, and this message is returned to a caller (`docs/09`).
    """
    # The filename is not the only thing a new dataset can collide with. Its
    # *declared* name decides where output lands, so a build that takes a name
    # another file already declares would make that file unreachable (the reader
    # refuses an ambiguous pair) and would send two datasets' output to one place.
    # `open("x")` guards the filename; this guards the name.
    taken = taken_dataset_names(configs_dir)
    if built.dataset_name in taken:
        raise ConfigurationError(
            f"the name {built.dataset_name!r} is already used by a dataset in this "
            "configuration directory, as either its file name or its declared "
            "dataset name; choose a different name"
        )
    path = config_path_for(configs_dir, built.dataset_name)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with path.open("x", encoding="utf-8") as handle:
            handle.write(built.to_yaml())
    except FileExistsError as exc:
        raise ConfigurationError(
            f"dataset {built.dataset_name!r} already exists; choose a different name "
            "rather than replacing a configuration that may be in use"
        ) from exc
    return path
