"""The config builder: a template plus a caller's choices become a validated dataset.

The builder owns **no** validation logic of its own beyond "is this choice on the
menu". Everything that decides whether a configuration is *correct* — does this chain
exist, is this parser registered, is this a known entity label, do the language
settings cohere — belongs to `config/loader.py`, which already knows how to say so
actionably. The builder assembles a document and hands it to that layer.

That split is the point rather than an economy: a service that could validate a
configuration the engine cannot would be owning engine knowledge, which ADR-0025's
rung rule forbids. If the builder ever needs an answer `config/` cannot give, the fix
is a change to `config/`.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

import yaml
from pydantic import ValidationError

from pii_reduction.config import known_labels
from pii_reduction.config.errors import ConfigurationError
from pii_reduction.config.loader import resolve_dataset
from pii_reduction.config.models import DatasetConfig, ProjectConfig
from pii_reduction.config.resolved import ResolvedDataset
from pii_reduction.service.catalog import taken_dataset_names
from pii_reduction.service.errors import InvalidRequestError, UnknownTemplateError
from pii_reduction.service.inbox import list_offered_files, resolve_offered_file
from pii_reduction.service.knobs import OFFERABLE_PARSER_OPTIONS
from pii_reduction.service.models import (
    DATASET_NAME_RE,
    BuildConfigRequest,
    ColumnRequest,
)
from pii_reduction.service.templates import DatasetTemplate

__all__ = ["BuiltConfig", "build_dataset_config", "config_path_for", "write_dataset_config"]


@dataclass(frozen=True)
class BuiltConfig:
    """A dataset document that has been through the config layer's own validation."""

    dataset_name: str
    template: str
    payload: dict[str, Any]
    resolved: ResolvedDataset
    #: True when a `select_file` template joined a caller's file name onto its
    #: directory, so the source path in `payload` is an absolute server path. Held
    #: because that changes what may be *returned* — see :meth:`to_response_yaml`.
    joined_source_path: bool = False

    def to_yaml(self) -> str:
        """The document as it is **written to disk**: complete and self-contained.

        The source path is absolute for a `select_file` template, which is what lets a
        later `pii-reduction run` read it with no memory of which template produced it
        and no dependence on a working directory.
        """
        return self._render(self.payload)

    def to_response_yaml(self) -> str:
        """The document as it is **returned to a caller**: the same, minus the root.

        `api.py` deliberately relativizes `saved_path` because "an absolute path is a
        server-environment string … and this value goes to a caller". The path this
        builder joins is exactly that: on a developer machine it carries an OS
        username, and on a workspace `/Volumes/<catalog>/<schema>/…` names a catalog
        and a schema, which `docs/09` puts on the unsafe side of a display surface.

        Returning the joined path would have broken that rule three lines from where
        it is enforced. The caller sees the directory as a placeholder and their own
        file name after it — they chose the file and the template chose the directory,
        so nothing they need is withheld — while the *saved* document, the one that
        actually runs, keeps the real path.
        """
        if not self.joined_source_path:
            return self._render(self.payload)
        payload = {**self.payload, "source": dict(self.payload["source"])}
        chosen = PurePosixPath(str(payload["source"]["path"])).name
        payload["source"]["path"] = f"<template directory>/{chosen}"
        return self._render(payload)

    def _render(self, payload: dict[str, Any]) -> str:
        header = (
            f"# Generated by the pii-reduction service layer (ADR-0026) from template\n"
            f"# {self.template!r}. Source, destination and the processing switches came\n"
            f"# from that template, not from the request.\n"
        )
        document: str = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
        return header + document


def _prune(value: Any) -> Any:
    """Drop empty containers and ``None`` so the generated YAML reads like a hand file."""
    if isinstance(value, dict):
        pruned = {k: _prune(v) for k, v in value.items() if v is not None}
        return {k: v for k, v in pruned.items() if v != {} and v != []}
    return value


def _require_on_menu(chosen: str, offered: tuple[str, ...], *, what: str, template: str) -> str:
    if chosen not in offered:
        raise InvalidRequestError(
            f"template {template!r} does not offer {what} {chosen!r}; "
            f"available: {', '.join(sorted(offered)) or '(none)'}"
        )
    return chosen


def _source_payload(template: DatasetTemplate, source_file: str | None) -> dict[str, Any]:
    """The template's source, with the chosen file name joined on when there is one.

    The **resolved absolute path** goes into the document rather than the name, so the
    generated configuration is self-contained: `pii-reduction run` reads it later with
    no memory of which template produced it, and a relative name would then resolve
    against whatever directory that process happens to be in.
    """
    payload: dict[str, Any] = _prune(template.source.model_dump(mode="json", by_alias=True))
    directory = template.offered_directory()
    if directory is None or source_file is None:
        return payload
    payload["path"] = resolve_offered_file(directory, source_file, template.source.type).as_posix()
    return payload


def _column_payload(
    request: ColumnRequest,
    template: DatasetTemplate,
    project: ProjectConfig,
    offered_entities: tuple[str, ...],
) -> dict[str, Any]:
    for label in request.entities:
        _require_on_menu(label, offered_entities, what="entity", template=template.name)
    payload: dict[str, Any] = {"entities": sorted(set(request.entities))}
    if request.parser is not None:
        payload["parser"] = _require_on_menu(
            request.parser, template.offered_parsers(), what="parser", template=template.name
        )
    if request.reducer is not None:
        payload["reducer"] = _require_on_menu(
            request.reducer, template.offered_reducers(), what="reducer", template=template.name
        )
    if request.provider_chain is not None:
        offered = template.provider_chains or tuple(sorted(project.chains))
        payload["provider_chain"] = _require_on_menu(
            request.provider_chain, offered, what="provider chain", template=template.name
        )
    if request.parser_options:
        # **The parser must be named in the same request.** Without it the builder
        # cannot tell whether the option is even valid — `split_lines` on a
        # `transcript` column is a ParserError raised when the *pipeline* is built,
        # which would mean a 201 here and a failed run later. A pre-flight check that
        # accepts a configuration which cannot run is worse than no check (ADR-0031).
        if request.parser is None:
            raise InvalidRequestError(
                f"column {request.column!r}: parser_options requires 'parser' to be set "
                f"in the same request, because an option is only valid for the parser "
                f"that defines it"
            )
        offered_options = template.offered_parser_options()
        accepted = OFFERABLE_PARSER_OPTIONS.get(request.parser, frozenset())
        for option in sorted(request.parser_options):
            _require_on_menu(option, offered_options, what="parser option", template=template.name)
            if option not in accepted:
                raise InvalidRequestError(
                    f"template {template.name!r} does not offer {option!r} for parser "
                    f"{request.parser!r}; it offers: "
                    f"{', '.join(sorted(accepted)) or '(none)'}"
                )
        # Sorted so the generated YAML is stable across requests that differ only in
        # key order — `config_hash` is computed from the resolved configuration and a
        # reordered mapping must not look like a different run.
        payload["parser_options"] = {
            option: request.parser_options[option] for option in sorted(request.parser_options)
        }
    return payload


def build_dataset_config(
    request: BuildConfigRequest,
    *,
    templates: dict[str, DatasetTemplate],
    project: ProjectConfig,
) -> BuiltConfig:
    """Assemble the document, then let the configuration layer accept or refuse it.

    Raises :class:`UnknownTemplateError` or :class:`InvalidRequestError` for a choice
    that is not on the menu, and lets `config`'s own ``ConfigurationError`` through
    for anything the configuration layer refuses — its messages name the field and
    the file and are already written to be shown to somebody.
    """
    template = templates.get(request.template)
    if template is None:
        raise UnknownTemplateError(
            f"unknown template {request.template!r}; "
            f"available: {', '.join(sorted(templates)) or '(none)'}"
        )

    _require_on_menu(
        request.row_id,
        template.offered_row_id_columns(),
        what="row id column",
        template=template.name,
    )

    # A file name is required exactly when the template offers a directory, and
    # refused otherwise — a name sent to a template with a fixed source would
    # otherwise be silently ignored, which is the failure mode `extra="forbid"` exists
    # to prevent everywhere else in this model.
    directory = template.offered_directory()
    if directory is None and request.source_file is not None:
        raise InvalidRequestError(
            f"template {template.name!r} has a fixed source and does not take a source_file"
        )
    if directory is not None and request.source_file is None:
        offered = list_offered_files(directory, template.source.type)
        raise InvalidRequestError(
            f"template {template.name!r} offers a directory: name one file with "
            f"source_file. Available: {', '.join(offered) or '(none)'}"
        )
    seen: set[str] = set()
    for column in request.columns:
        _require_on_menu(column.column, template.columns, what="column", template=template.name)
        if column.column in seen:
            raise InvalidRequestError(f"column {column.column!r} is listed twice")
        seen.add(column.column)
        if column.column == request.row_id:
            raise InvalidRequestError(
                f"column {request.row_id!r} is the row identifier and cannot also be reduced"
            )

    offered_entities = template.entities or tuple(sorted(known_labels()))
    payload: dict[str, Any] = {
        "dataset": {"name": request.dataset_name, "row_id": request.row_id},
        "source": _source_payload(template, request.source_file),
        "destination": _prune(template.destination.model_dump(mode="json", by_alias=True)),
        "columns": {
            column.column: _column_payload(column, template, project, offered_entities)
            for column in request.columns
        },
    }
    if template.processing is not None:
        processing = _prune(template.processing.model_dump(mode="json"))
        if processing:
            payload["processing"] = processing
    if template.language is not None:
        language = _prune(template.language.model_dump(mode="json"))
        if language:
            payload["language"] = language

    try:
        dataset = DatasetConfig.model_validate(payload)
    except ValidationError as exc:
        # A pydantic error here is a *configuration* problem — almost always a
        # template field the dataset model refuses — and must not reach the API's
        # last-resort handler as `unexpected ValidationError`. Rendered as
        # `field.path: message`, never echoing the offending value.
        details = "; ".join(
            f"{'.'.join(str(part) for part in error['loc']) or '<root>'}: {error['msg']}"
            for error in exc.errors()
        )
        raise ConfigurationError(
            f"template {template.name!r} cannot produce a valid dataset ({details})"
        ) from exc
    resolved = resolve_dataset(dataset, project)
    return BuiltConfig(
        dataset_name=request.dataset_name,
        template=template.name,
        payload=payload,
        resolved=resolved,
        joined_source_path=request.source_file is not None,
    )


def config_path_for(configs_dir: Path, dataset_name: str) -> Path:
    """Where a built config is written. Derived by the server, never sent by a caller.

    ``dataset_name`` has already been validated against
    :data:`~pii_reduction.service.models.DATASET_NAME_PATTERN`, so it cannot contain a
    separator, a dot or a leading digit — the property that makes this a join rather
    than a path-traversal surface. Re-checked here anyway, because this function is
    reachable from anywhere in the package and the check is one line.
    """
    if not DATASET_NAME_RE.match(dataset_name):
        raise InvalidRequestError(
            f"dataset name {dataset_name!r} is not a valid identifier "
            "(lower-case letters, digits and underscores; 3-64 characters)"
        )
    return configs_dir / "datasets" / f"{dataset_name}.yaml"


def write_dataset_config(built: BuiltConfig, configs_dir: Path) -> Path:
    """Write the document, refusing to replace one that exists.

    Fail-closed for the same reason ``errorifexists`` is the Delta default: a builder
    that silently overwrites a configuration somebody is running turns a naming
    collision into a change of behaviour for a job nobody edited.

    ``open(..., "x")`` rather than ``exists()`` then write: the check and the write are
    one operation, so two requests naming the same dataset cannot both pass the check.
    The message names the **dataset**, not the path — a path is a server-environment
    string, and this message is returned to a caller (`docs/09`).
    """
    # The filename is not the only thing a new dataset can collide with. Its
    # *declared* name decides where output lands, so a build that takes a name
    # another file already declares would make that file unreachable (the reader
    # refuses an ambiguous pair) and would send two datasets' output to one place.
    # `open("x")` guards the filename; this guards the name.
    taken = taken_dataset_names(configs_dir)
    if built.dataset_name in taken:
        raise ConfigurationError(
            f"the name {built.dataset_name!r} is already used by a dataset in this "
            "configuration directory, as either its file name or its declared "
            "dataset name; choose a different name"
        )
    path = config_path_for(configs_dir, built.dataset_name)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with path.open("x", encoding="utf-8") as handle:
            handle.write(built.to_yaml())
    except FileExistsError as exc:
        raise ConfigurationError(
            f"dataset {built.dataset_name!r} already exists; choose a different name "
            "rather than replacing a configuration that may be in use"
        ) from exc
    return path
